// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<CANTalon> driveTrainrightTopMotor;
	static std::shared_ptr<CANTalon> driveTrainrightFrontMotor;
	static std::shared_ptr<CANTalon> driveTrainrightRearMotor;
	static std::shared_ptr<CANTalon> driveTrainleftRearMotor;
	static std::shared_ptr<CANTalon> driveTrainleftTopMotor;
	static std::shared_ptr<CANTalon> driveTrainleftFrontMotor;
	static std::shared_ptr<DoubleSolenoid> driveTrainshiftSolenoid;
	static std::shared_ptr<Compressor> pneumaticsCompressor;
	static std::shared_ptr<AnalogInput> pneumaticspressureSensor;
	static std::shared_ptr<CANTalon> pivotpivotMotor;
	static std::shared_ptr<DigitalInput> pivotPivotLowerLimit;
	static std::shared_ptr<Encoder> pivotPivotEncoder;
	static std::shared_ptr<DigitalInput> pivotPivotUpperLimit;
	static std::shared_ptr<CANTalon> shooterrightFlywheelMotor;
	static std::shared_ptr<CANTalon> shooterleftFlywheelMotor;
	static std::shared_ptr<Solenoid> shooterkickerSolenoid;
	static std::shared_ptr<CANTalon> collectorrightCollectorMotor;
	static std::shared_ptr<CANTalon> collectorleftCollectorMotor;
	static std::shared_ptr<CANTalon> collectorrollerMotor;
	static std::shared_ptr<DigitalInput> collectorcollectorArmUpSwitch;
	static std::shared_ptr<DigitalInput> collectorcollectorArmDownSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
