// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::driveTrainLeftFrontDrive;
std::shared_ptr<CANTalon> RobotMap::driveTrainLeftRearDrive;
std::shared_ptr<CANTalon> RobotMap::driveTrainLeftTopDrive;
std::shared_ptr<CANTalon> RobotMap::driveTrainRightTopDrive;
std::shared_ptr<CANTalon> RobotMap::driveTrainRightFrontDrive;
std::shared_ptr<CANTalon> RobotMap::driveTrainRightRearDrive;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveTrainLeftFrontDrive.reset(new CANTalon(6));
    lw->AddActuator("DriveTrain", "LeftFrontDrive", driveTrainLeftFrontDrive);
    
    driveTrainLeftRearDrive.reset(new CANTalon(4));
    lw->AddActuator("DriveTrain", "LeftRearDrive", driveTrainLeftRearDrive);
    
    driveTrainLeftTopDrive.reset(new CANTalon(5));
    lw->AddActuator("DriveTrain", "LeftTopDrive", driveTrainLeftTopDrive);
    
    driveTrainRightTopDrive.reset(new CANTalon(1));
    lw->AddActuator("DriveTrain", "RightTopDrive", driveTrainRightTopDrive);
    
    driveTrainRightFrontDrive.reset(new CANTalon(2));
    lw->AddActuator("DriveTrain", "RightFrontDrive", driveTrainRightFrontDrive);
    
    driveTrainRightRearDrive.reset(new CANTalon(3));
    lw->AddActuator("DriveTrain", "RightRearDrive", driveTrainRightRearDrive);
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
