// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveTrain: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<CANTalon> rightTopMotor;
	std::shared_ptr<CANTalon> rightFrontMotor;
	std::shared_ptr<CANTalon> rightRearMotor;
	std::shared_ptr<CANTalon> leftRearMotor;
	std::shared_ptr<CANTalon> leftTopMotor;
	std::shared_ptr<CANTalon> leftFrontMotor;
	std::shared_ptr<DoubleSolenoid> shiftSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	const float FORWARD = 1;
	const float REVERSE = -1;
	const float rightTopDirection = FORWARD;
	const float rightFrontDirection = REVERSE;
	const float rightRearDirection = REVERSE;
	const float leftTopDirection = REVERSE;
	const float leftFrontDirection = FORWARD;
	const float leftRearDirection = FORWARD;

public:
	DriveTrain();
	void InitDefaultCommand();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	void RunDriveTrainMotors(float rightSpeed, float leftSpeed, float baseDirection);
	void StopBase();
	void DownShift();
	void UpShift();
	void ToggleShift();
	void DriveForward(float speed);
	void DriveBackward(float speed);
};

#endif
