// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "shiftDriveBase.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

shiftDriveBase::shiftDriveBase(int shiftState): Command() {
    m_shiftState = shiftState;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
/*
 * kForward is low gear, kReverse is high gear.  Start in low gear.
 */
/* Called just before this Command runs the first time.  If it is already in
* low gear, this won't really do anything
*/
void shiftDriveBase::Initialize()
{
//	DriveTrain::DownShift();
}

// Called repeatedly when this Command is scheduled to run
void shiftDriveBase::Execute()
{
//	DriveTrain::ToggleShift();

}

// Make this return true when this Command no longer needs to run execute()
bool shiftDriveBase::IsFinished()
{
    return false;
}

// Called once after isFinished returns true
void shiftDriveBase::End()
{

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void shiftDriveBase::Interrupted()
{

}
